# Generated by Django 5.0.3 on 2024-03-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='selected_choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='report',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='report',
            name='survey',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='generated_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
