# Generated by Django 5.0.3 on 2024-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_text',
            field=models.TextField(default='Default Text', max_length=255),
        ),
    ]
