# Generated by Django 5.0.3 on 2024-04-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_report_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_text',
        ),
    ]
