# Generated by Django 5.0.4 on 2024-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('currency_code', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('tags', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
