# Generated by Django 5.0.4 on 2024-07-08 17:14

import django.contrib.postgres.fields
import django.core.validators
import store.common.models
import store.listings.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', store.common.models.PriceField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48000)])),
                ('currency_code', models.CharField(default='EUR', max_length=3, validators=[store.listings.models.validate_currency])),
                ('description', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
