# Generated by Django 5.0.4 on 2024-07-22 15:13

import django.core.validators
import store.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=store.common.fields.PriceField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4800000)]),
        ),
    ]
