# Generated by Django 5.0.4 on 2024-08-22 15:27

import store.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency_code',
            field=models.CharField(default='eur', max_length=3, validators=[store.listings.models.validate_currency]),
        ),
    ]
